### ISSUE TITLE
Issues building with MS Visual Studio 14 Win64

### ISSUE THREAD

**Issue by cpace6** [lasote/conan-gtest#13]
Hi,
I've been running into a couple of issues trying to build this with MS Visual Studio 14. 
I'm following the conan-gtest-example in the conan docs (http://docs.conan.io/en/latest/examples/gtest.html) 

Other than using a different compiler, I am essentially following the tutorial directly:

1. Run "conan install"
2. **cd** to the build directory
3. Run 'cmake -G "Visual Studio 14 Win64" -DBUILD_TEST=TRUE ..', 
4. Open the .sln file, 
5. Build Solution in Visual Studio 

The project builds successfully, but I see 26 warnings- C4996 twice, C4251 twenty-one times, C4275 twice, and C4267 once. 

I have seen the same issues when trying to use this package with other projects. Here are my conaninfo settings: 
[settings]
    arch=x86_64
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=14
    os=Windows

I am seeing a different set of issues when trying to build this package in the same configuration with static libs (gtest:shared=False). When using static libs, the project builds fine with no warnings or errors in Release mode, but in Debug mode it is unsuccessful. Here are the errors/warnings I'm seeing: LNK2038 (4 times), LNK4098 (twice), and LNK1319 (twice)

**Comment by lasote** [comment]
Hi @cpace6. About the Warnings, What I can see are errors in gtest.h code, not related with conan package. Maybe we could try to upgrade to gtest 1.8 and see if have been fixed some warns.
About the errors, I've tried to build it shared/static/debug/release and it works fine. No errors detected, with latest Visual Studio.

**Comment by cpace6** [comment]
Thanks for the quick response @lasote 

I think upgrading to gtest 1.8 is worth a shot to see if it takes care of some of those warnings.

It's interesting that you don't see the errors so I will try to provide more details about what I'm doing. I'm seeing these errors whenever I try to build in static/debug. After setting *gtest:shared=False* in **conanfile.txt**, I'm following steps 1-5 above, then Building Solution in VS with Solution Configuration = Debug. Specifically these are the errors I'm seeing: 
<img width="1050" alt="debugstaticbuilderrors" src="https://cloud.githubusercontent.com/assets/18432608/19969144/d661afa4-a1ad-11e6-8051-6d399e992d47.PNG">

I am seeing the exact same set of errors & warnings in my personal project which uses the same package. Are the steps you're following any different from what I'm doing?

**Comment by lasote** [comment]
I got it. The errors are produced because you have installed the gtest library with build_type setting "Release" and then you are trying to compile with Debug in Visual Studio. 
If you want to change the build_type of your dependencies in a conan project you need to specify it in the conan install command:

`conan install -s build_type=Debug -s compiler="Visual Studio" -s compiler.version=14 -s compiler.runtime=MDd`

Then you can continue with the five steps.
If you don't want to type all the settings (a little annoying) we recently released the "profiles" feature, you can define a file "vs14debug" in your **.conan/profiles** directory like this:

```
[settings]
compiler=Visual Studio
compiler.version=14
build_type=Debug
compiler.runtime=MDd
```

And then use the profile in the install:

`conan install --profile vs14debug`

**Comment by lasote** [comment]
PD: I'm working in the gtest 1.8 version

**Comment by cpace6** [comment]
Thanks! I can now get it to build in Debug mode. 

I am still a bit unsure about this though. When building with the steps above but using shared .dlls (gtest:shared=True), I am able to compile successfully in both Release and Debug, but with static libs I can only choose one or the other. Is there any way to build for both Release and Debug with static libs?

**Comment by lasote** [comment]
I think it doesn't crash because the windows/dll internals. The error is about the different runtimes and debug symbols, maybe using a dll is less problematic with these kind of error, but as I said, it's a windows behavior, mixing debug/release should break the build, but not always.

To ease the debug/release change I could suggest some alternatives:

1. Develop in debug and change to release manually when you are ready.
2. Automate the build with a simple script that makes the install and builds iin command line with "cmake --build --config Release ." instead of opening Visual Studio
3. Have 2 "build" folders one for release and one for debug, with different visual studio projects (or build from code)

**Comment by cpace6** [comment]
Thanks a lot for the help and suggestions! 

Any eta of when the gtest 1.8 version will be ready?

**Comment by lasote** [comment]
It's ready! sorry for not warn you before.

**Comment by cpace6** [comment]
I tried to build again with the gtest 1.8.0 package and unfortunately I'm still seeing the same warnings. Thanks anyway though.
