### ISSUE TITLE
GTest with or without gtest_main

### ISSUE THREAD

**Issue by mropert** [lasote/conan-gtest#15]
GTest leaves the option to link to both gtest and gtest_main, or only gtest and provide your own main() function.
I'm curious how conan could handle this.
We could make two packages but that would require 2 builds...

**Comment by lasote** [comment]
We could introduce an option to the recipe, and use it for link or not the gtest_main in the `package_info` method.

**Comment by absassi** [comment]
Hi,

I'd like to add that since gmock is now part of gtest since version 1.8.0. Therefore, there is both `gtest_main` and `gmock_main`, which leaves the developer with four linkage options:

* `gtest` - custom main
* `gtest`, `gtest_main` - standard main
* `gtest`, `gmock` - custom main and gmock
* `gtest`, `gmock`, `gmock_main` - standard main and gmock

I've locally added the options:

* `"gmock": [True, False]` (default `True`, because even if unused this is hardly a problem)
* `"main": [True, False]` (default `True`, because of backward compatibility and I believe it is more common too)

Would you like me to send a PR?

**Comment by lasote** [comment]
Yes please, but the introduced options should be defaulted to "false" to not change the default packages IDs, that way the same binary packages can be reused, so:

- `"no_mock": [True, False]`default False
- `"no_main": [True, False]`default False

Is it ok? Thanks @absassi

**Comment by absassi** [comment]
Ok, thanks. I didn't know adding options with default False would give the same the package ID.
